students/cfarris/Hello_World.txt
=> Commiting a simple .txt file

students/ZackConnaughton/README.txt
=> Added a student folder for ZackConnaughton, and a README.txt file

students/DiannaTingg/README.md
Added student folder and readme file
=> Added student folder and readme file

students/BrianNisonger/readme.txt
=> Readme file

students/Kate_Koehn/Lesson01/Assignment/inventory_management/.idea/inventory_management.iml, students/Kate_Koehn/Lesson01/Assignment/inventory_management/.idea/misc.xml, students/Kate_Koehn/Lesson01/Assignment/inventory_management/.idea/modules.xml, students/Kate_Koehn/Lesson01/Assignment/inventory_management/.idea/workspace.xml, students/Kate_Koehn/Lesson01/Assignment/inventory_management/electric_appliances_class.py, students/Kate_Koehn/Lesson01/Assignment/inventory_management/furniture_class.py, students/Kate_Koehn/Lesson01/Assignment/inventory_management/inventory_class.py, students/Kate_Koehn/Lesson01/Assignment/inventory_management/main.py, students/Kate_Koehn/Lesson01/Assignment/inventory_management/market_prices.py, students/Kate_Koehn/Lesson01/Assignment/inventory_management/menu.py, students/Kate_Koehn/Lesson01/Assignment/test_file.py
Not quite finished, ran out of time. Used patch from unittest.mock instead of MagicMock to test input.
=> Uploading assignment 1 - Inventory Management

students/ZidanLuo/Lesson01/calculator/adder.py, students/ZidanLuo/Lesson01/calculator/calculator.py, students/ZidanLuo/Lesson01/calculator/divider.py, students/ZidanLuo/Lesson01/calculator/exceptions.py, students/ZidanLuo/Lesson01/calculator/multiplier.py, students/ZidanLuo/Lesson01/calculator/subtracter.py, students/ZidanLuo/Lesson01/test_integration.py, students/ZidanLuo/Lesson01/test_unit.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/.pylintrc, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/electric_appliances_class.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/furniture_class.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/inventory_class.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/main.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/inventory_management/market_prices.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/main.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/test_integration.py, students/ZidanLuo/lessons/lesson01/Assignments/Assignment01/test_unit.py
the assignment is not finished yet, still has importing issues
=> added files for lesson01 assignment

students/BrianNisonger/Lesson3/assignment/basic_operations.py, students/BrianNisonger/Lesson3/assignment/create_customer.py, students/BrianNisonger/Lesson3/assignment/customer_model.py, students/BrianNisonger/Lesson3/assignment/test_customer_db.py
Adding code and tests.  If I have additional time I will add more tests.  Everything runs and all tests pass.
=> Adding my completed code for Lesson 3. 

students/ZidanLuo/lessons/lesson03/assignment/basic_operations.py, students/ZidanLuo/lessons/lesson03/assignment/create_customer.py, students/ZidanLuo/lessons/lesson03/assignment/customer_model.py, students/ZidanLuo/lessons/lesson03/assignment/test_basic_operations.py
=> added lesson3 assignments

students/BrianNisonger/Lesson4/basic_operations.py, students/BrianNisonger/Lesson4/test_customer_db.py
Added iteration.  Added bulk insert to add_customer. Modified search customer to use comprehension. Modified update_customer_credit to update_customer and am now using whatever keywords are used to call it to determine what elements to update Ex: update_customer(customer_id='12234',status=True,credit_limit=100.0) will now update the status and the credit limit.  Slightly modified the test cases in order to make code work, but all minor changes.
=> Added iteration

students/KyleBarry/lesson03/basic_operations.py, students/KyleBarry/lesson03/test_customer.py
Bulk add customers function created.
=> Bulk add customers

students/BrianNisonger/Lesson5/assignment/database.py, students/BrianNisonger/Lesson5/assignment/test_database.py
New assignment, using fixtures, a set of CSV files, and MongoDB.  I am including both the code and the tests.
=> Lesson 5 assignment

students/Kate_Koehn/Lesson06/Log of changes made to good_perf.rtf, students/Kate_Koehn/Lesson06/good_perf.py, students/Kate_Koehn/Lesson06/poor_perf.py, students/Kate_Koehn/Lesson06/test_perf_output.py
Good_perf.py (updates made to poor_perf.py), poor_perf.py (original file), Log of changes made to code and performance changes, & test file to check that the output remained the same the whole time.
=> Submitting week 6 homework files

students/DiannaTingg/lessons/lesson06/assignment/good_perf.py, students/DiannaTingg/lessons/lesson06/assignment/notes.txt, students/DiannaTingg/lessons/lesson06/assignment/poor_perf.py, students/DiannaTingg/lessons/lesson06/assignment/test_good_perf.py
I refactored the code in good_perf.py and I created one test.  All of my notes are in notes.txt.  
I got the function down to 6.8 seconds, but not sure how to make it any faster.
Thank you!
=> Added assignment files under lesson06

students/DrewSmith/lessons/lesson06/assignment/Perf_notes.txt, students/DrewSmith/lessons/lesson06/assignment/good_perf.py, students/DrewSmith/lessons/lesson06/assignment/poor_perf.py
Poor Performance Timeit: **9.248711s**
Good Performance Timeit: **2.04s**
Final with datetime parsing: **16.5s**
SUMMARY: Biggest performance increases were from 
1. Removing duplicate looping (original was looping over data 2.5 times)
2. Switching from CSV library parsing to just using file.readline() to get the line string and slicing the values needed using .rfind(',') to get last comma index
Detailed notes on what I tried (both good and bad) are in the Perf_notes.txt file.
Per your Slack note I tried datetime parsing. Was able to go from 71 seconds using dateutils.parse down to 16.5 using datetime.strptime().
Datetime parsing code is commented out in my code.
The poor_perf.py code had this possible bug, but I coded as though that was a feature. (2018 gets counted into 2017).
Fixing …
=> Assignment 6

students/Zach Cooper/lesson06/Description of Changes Made to good_perf.py, students/Zach Cooper/lesson06/alt_good_perf.py, students/Zach Cooper/lesson06/good_perf.py, students/Zach Cooper/lesson06/poor_perf.py, students/Zach Cooper/lesson06/test_good_perf.py
I created to different .py files to compare results for this assignment. good_perf converts datetime strings to date objects which we did in office hours but output time is just too long. alt_good_perf keeps the dates as strings and is much quicker. Where could I change code in good_perf to possibly make it faster? Not sure there is much more I can do since the majority of the time it takes is directed towards converting all the datetimes.
Thanks.
=> Added lesson06 Assignment

students/JaeKim/lesson07/assignment/customers.csv, students/JaeKim/lesson07/assignment/database.py, students/JaeKim/lesson07/assignment/linear.py, students/JaeKim/lesson07/assignment/parallel.py, students/JaeKim/lesson07/assignment/products.csv, students/JaeKim/lesson07/assignment/rentals.csv, students/JaeKim/lesson07/assignment/sample_csv_files/README.md, students/JaeKim/lesson07/assignment/test_database.py
Updated 'import_data' to use threads.
=> Assignment7

students/DiannaTingg/lessons/lesson07/activity/locking.py, students/DiannaTingg/lessons/lesson07/activity/semaphore.py, students/DiannaTingg/lessons/lesson07/assignment/customers.csv, students/DiannaTingg/lessons/lesson07/assignment/findings.txt, students/DiannaTingg/lessons/lesson07/assignment/linear.py, students/DiannaTingg/lessons/lesson07/assignment/parallel.py, students/DiannaTingg/lessons/lesson07/assignment/products.csv, students/DiannaTingg/lessons/lesson07/assignment/rentals.csv, students/DiannaTingg/lessons/lesson07/assignment/test_linear.py, students/DiannaTingg/lessons/lesson07/assignment/test_parallel.py
Per the assignment requirements, I changed linear.py so that it returns two tuples, one for customers and one for products.
My version using multithreading is in parallel.py.  It seems a little bit faster, but not by much.  I had a difficult time returning values from the threads, so I passed in a dictionary.  I also wasn't sure if I had to add any locking, so I assume the GIL is taking care of that for me.  :-)  
I made some tests for both files and all of them pass.  My notes are in findings.txt.  Thank you!
=> Added assignment files under lesson07

students/Kate_Koehn/Lesson07/Findings.rtf, students/Kate_Koehn/Lesson07/linear.py, students/Kate_Koehn/Lesson07/parallel.py
Submitting linear.py, parallel.py, and Findings.rtf
=> Submitting files for week 7 homework

students/DrewSmith/lessons/lesson08/assignment/inventory.py, students/DrewSmith/lessons/lesson08/assignment/test_inventory.py, students/DrewSmith/lessons/lesson08/assignment/test_items.csv
Inventory.py and some pytest tests for the required functions.
=> Assignment 08 inventory files

students/Kate_Koehn/Lesson08/inventory.py, students/Kate_Koehn/Lesson08/invoice_file.csv, students/Kate_Koehn/Lesson08/susans_stuff.csv, students/Kate_Koehn/Lesson08/test_data.csv
Submitting homework 8 and all relevant files associated with it.
=> submitting files for homework 8

students/Zach Cooper/lesson07/Changes Made.txt, students/Zach Cooper/lesson07/linear.py, students/Zach Cooper/lesson07/parallel.py, students/Zach Cooper/lesson08/inventory.py, students/Zach Cooper/lesson08/invoice_file.txt, students/Zach Cooper/lesson08/susans_stuff.txt, students/Zach Cooper/lesson08/test_data.txt
=> Added Lesson07 and Lesson08 Material

students/Kate_Koehn/Lesson09/jpgdiscover.py, students/Kate_Koehn/Lesson09/logging_decorators.py, students/Kate_Koehn/Lesson10/database.py, students/Kate_Koehn/Lesson10/timing_output.txt
Part 1 still stops all logging vs just stopping the logging of the decorated function. Still working on that.
=> Adding parts 1 & 3 of HW 9

students/ericstreit/lessons/lesson04/assignment/create_customers.py, students/ericstreit/lessons/lesson04/assignment/create_db.py, students/ericstreit/lessons/lesson04/assignment/db_model.py, students/ericstreit/lessons/lesson05/assignment/database.py, students/ericstreit/lessons/lesson09/assignment/database.py, students/ericstreit/lessons/lesson09/assignment/jpgdiscover.py, students/ericstreit/lessons/lesson09/assignment/jpgdiscover0.py, students/ericstreit/lessons/lesson09/assignment/logging_assignment/charges_calc.py, students/ericstreit/lessons/lesson10/assignment/database.py
A bunch of Lesson10 as well but still need to provide test results on the timing
=> Lesson05 completed (mongodb)
